# -*- coding: utf-8 -*-
# Seed 3 — categorias 15..22
TOOLS_3 = [
# 15. Automação de tarefas e agentes
dict(n="Zapier (AI Agents)", u="https://zapier.com", c1=15, f="Automação no-code com agentes de IA", a="Equipes e pequenos negócios", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Make (Integromat)", u="https://www.make.com", c1=15, f="Automação visual com módulos de IA", a="Profissionais e empresas", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="n8n", u="https://n8n.io", c1=15, f="Automação de workflows open source com nós de IA", a="Desenvolvedores e empresas", p="Cloud, self-hosted, API", c="open source", r="sim", api="sim", os="sim", reg="mundial", doc="https://docs.n8n.io"),
dict(n="Activepieces", u="https://www.activepieces.com", c1=15, f="Automação open source com recursos de IA", a="Desenvolvedores e PMs", p="Cloud, self-hosted", c="open source", r="sim", api="sim", os="sim", reg="mundial", doc=""),
dict(n="LangChain", u="https://www.langchain.com", c1=15, f="Framework para construir agentes e pipelines de LLM", a="Desenvolvedores", p="Biblioteca (Python/JS), cloud", c="open source", r="não", api="sim", os="sim", reg="mundial", doc="https://docs.langchain.com"),
dict(n="LangGraph", u="https://www.langchain.com/langgraph", c1=15, f="Orquestração de agentes com estados (open source)", a="Desenvolvedores", p="Biblioteca, cloud", c="open source", r="não", api="sim", os="sim", reg="mundial", doc="https://langchain-ai.github.io/langgraph"),
dict(n="CrewAI", u="https://www.crewai.com", c1=15, f="Framework de agentes colaborativos (open source)", a="Desenvolvedores", p="Biblioteca (Python)", c="open source", r="não", api="sim", os="sim", reg="mundial", doc="https://docs.crewai.com"),
dict(n="AutoGen (Microsoft)", u="https://microsoft.github.io/autogen", c1=15, f="Framework de agentes multi-agente da Microsoft", a="Desenvolvedores", p="Biblioteca (Python)", c="open source", r="não", api="não", os="sim", reg="mundial", doc="https://microsoft.github.io/autogen"),
dict(n="AgentGPT", u="https://agentgpt.reworkd.ai", c1=15, f="Agentes autônomos no navegador", a="Curiosos e devs", p="Web", c="open source", r="não", api="não", os="sim", reg="mundial", doc="https://github.com/reworkd/AgentGPT"),
dict(n="AutoGPT", u="https://agpt.co", c1=15, f="Agente autônomo open source para tarefas", a="Desenvolvedores", p="CLI, local", c="open source", r="não", api="não", os="sim", reg="mundial", doc="https://docs.agpt.co"),
dict(n="Flowise", u="https://flowiseai.com", c1=15, f="Criação visual de fluxos de LLM (open source)", a="Desenvolvedores e PMs", p="Self-hosted, cloud, API", c="open source", r="sim", api="sim", os="sim", reg="mundial", doc="https://docs.flowiseai.com"),
dict(n="Dify", u="https://dify.ai", c1=15, f="Plataforma de apps LLM com RAG e agentes (open source)", a="Empresas e devs", p="Cloud, self-hosted, API", c="open source", r="sim", api="sim", os="sim", reg="mundial", doc="https://docs.dify.ai"),
dict(n="Lindas (Lindy)", u="https://www.lindy.ai", c1=15, f="Agentes de IA para automação de operações", a="Empresas", p="Web", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Apify", u="https://apify.com", c1=15, f="Automação de web scraping e agentes", a="Desenvolvedores e analistas", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc="https://docs.apify.com"),
dict(n="Browserbase (dev)", u="https://www.browserbase.com", c1=15, f="Infraestrutura de navegador para agentes", a="Desenvolvedores", p="API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Browser Use (framework)", u="https://browser-use.com", c1=15, f="Framework open source para agentes de navegador", a="Desenvolvedores", p="Biblioteca (Python)", c="open source", r="não", api="sim", os="sim", reg="mundial", doc="https://docs.browser-use.com"),
# 16. Marketing, publicidade e SEO
dict(n="Semrush (AI)", u="https://www.semrush.com", c1=16, f="SEO, pesquisa de palavras-chave e marketing com IA", a="Marketers e agências", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Ahrefs (AI)", u="https://ahrefs.com", c1=16, f="SEO e análise de backlinks com ferramentas de IA", a="SEO e marketers", p="Web", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Surfer SEO", u="https://surferseo.com", c1=16, f="Otimização de conteúdo para SEO com IA", a="Marketers e SEO", p="Web, extensão, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Frase.io", u="https://www.frase.io", c1=16, f="Criação e otimização de conteúdo SEO com IA", a="Marketers", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Jasper (marketing)", u="https://www.jasper.ai", c1=16, f="Copywriting e campanhas com IA", a="Marketers", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="AdCreative.ai", u="https://www.adcreative.ai", c1=16, f="Criação de criativos de anúncios com IA", a="Marketers e agências", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Photoroom (ads)", u="https://www.photoroom.com", c1=16, f="Imagens de produtos para anúncios com IA", a="E-commerce e marketplaces", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="HubSpot AI", u="https://www.hubspot.com", c1=16, f="CRM com assistentes de IA para marketing e vendas", a="Empresas", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Mailchimp (AI)", u="https://mailchimp.com", c1=16, f="Email marketing com geração de conteúdo por IA", a="Pequenos negócios", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Klaviyo AI", u="https://www.klaviyo.com", c1=16, f="Email/SMS marketing com IA para e-commerce", a="E-commerce", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Copy.ai (go-to-market)", u="https://www.copy.ai", c1=16, f="Geração de textos de GTM e vendas", a="Startups e vendas", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="NeuronWriter", u="https://www.neuronwriter.com", c1=16, f="Otimização semântica de conteúdo com IA", a="SEO", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Topic (by MarketMuse)", u="https://www.marketmuse.com", c1=16, f="Pesquisa de tópicos com IA para conteúdo", a="Marketers e SEO", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="La Growth Machine", u="https://lagrowthmachine.com", c1=16, f="Automação de prospecção e vendas (LinkedIn/email) com IA", a="Vendas e marketing B2B", p="Web", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Brand24 AI", u="https://brand24.com", c1=16, f="Monitoramento de marca e insights com IA", a="Marketers e PR", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Mention (IA)", u="https://mention.com", c1=16, f="Monitoramento social e de marca com IA", a="Marketers", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Blotato", u="https://www.blotato.com", c1=16, f="Copywriting em vários idiomas com IA", a="Marketers", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
# 17. Redes sociais e criação de conteúdo
dict(n="Buffer (IA)", u="https://buffer.com", c1=17, f="Agendamento social com assistente de IA", a="Marketers e creators", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Hootsuite (OwlyWriter IA)", u="https://www.hootsuite.com", c1=17, f="Gestão de redes sociais com IA", a="Equipes e agências", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Sprout Social (IA)", u="https://sproutsocial.com", c1=17, f="Plataforma social com insights de IA", a="Empresas", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="FeedHive", u="https://feedhive.com", c1=17, f="Agendamento e criação de posts com IA", a="Creators", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Postiz (open source)", u="https://postiz.com", c1=17, f="Agendamento social open source com IA", a="Creators e agências", p="Web, self-hosted", c="open source", r="sim", api="não", os="sim", reg="mundial", doc="https://github.com/gitroomhq/postiz-app"),
dict(n="Metricool (IA)", u="https://metricool.com", c1=17, f="Analytics e agendamento social com IA", a="Creators e agências", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Lately AI", u="https://www.lately.ai", c1=17, f="Geração de posts a partir de conteúdo existente", a="Marketers", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Canva (Magic para social)", u="https://www.canva.com", c1=17, f="Design de posts com IA (Magic Design)", a="Creators e negócios", p="Web, apps", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Vista Social (IA)", u="https://vistasocial.com", c1=17, f="Gestão social com assistente de IA", a="Agencias", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Tweet Hunter", u="https://tweethunter.io", c1=17, f="Crescimento no X/Twitter com IA", a="Creators", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Typefully", u="https://typefully.com", c1=17, f="Escrita e agendamento de threads com IA", a="Creators", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Submagic", u="https://www.submagic.co", c1=17, f="Legendas e clipes para Shorts/Reels/TikTok", a="Creators", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Reveal (crescimento)", u="https://revealbot.com", c1=17, f="Automação de anúncios sociais com IA", a="Marketers", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Notion (IA social)", u="https://www.notion.so", c1=17, f="Gestão de conteúdo e calendário com IA", a="Creators e equipes", p="Web, apps", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Missinglettr", u="https://missinglettr.com", c1=17, f="Automatização de posts a partir de blogs", a="Marketers", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Zapier (IA social)", u="https://zapier.com", c1=17, f="Automações sociais com IA", a="Profissionais", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
# 18. Design gráfico e criação de logotipos
dict(n="Canva", u="https://www.canva.com", c1=18, f="Design gráfico com ferramentas de IA", a="Público geral e designers", p="Web, apps", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Figma (AI)", u="https://www.figma.com", c1=18, f="Design de interfaces com assistente de IA", a="Designers de UI/UX", p="Web, desktop", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Looka", u="https://looka.com", c1=18, f="Criação de logotipos com IA", a="Startups e pequenos negócios", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Hocoos Logo Maker (IA)", u="https://hocoos.com", c1=18, f="Gerador de logotipos com IA", a="Pequenos negócios", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Brandmark", u="https://brandmark.io", c1=18, f="Design de logotipo com IA", a="Startups", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Hatchful (Shopify)", u="https://hatchful.shopify.com", c1=18, f="Gerador de logos gratuito da Shopify", a="Lojistas", p="Web", c="gratuito", r="não", api="não", os="não", reg="mundial", doc=""),
dict(n="Adobe Illustrator (IA)", u="https://www.adobe.com/products/illustrator.html", c1=18, f="Vetor com recursos generativos", a="Designers profissionais", p="Windows, macOS", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Ideogram (logo)", u="https://ideogram.ai", c1=18, f="Geração de logos com texto preciso", a="Designers", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Logo.com", u="https://logo.com", c1=18, f="Criação de logos com IA", a="Pequenos negócios", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Designs.ai", u="https://designs.ai", c1=18, f="Suíte de design com IA (logo, vídeo, fala)", a="Agencias e negócios", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="VistaCreate (IA)", u="https://create.vista.com", c1=18, f="Design de posts e marketing com IA", a="Pequenos negócios", p="Web, apps", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Placeit", u="https://placeit.net", c1=18, f="Mockups e designs com IA", a="Marketers e lojistas", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Flair AI", u="https://flair.ai", c1=18, f="Design de embalagens e produtos com IA", a="E-commerce", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="DALL·E via ChatGPT (design)", u="https://chatgpt.com", c1=18, f="Geração de assets de design via ChatGPT", a="Designers", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Uizard", u="https://uizard.io", c1=18, f="Design de UI a partir de texto ou captura (IA)", a="PMs e designers", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
# 19. Educação e aprendizagem
dict(n="Khan Academy (Khanmigo)", u="https://www.khanmigo.ai", c1=19, f="Tutor de IA para alunos e professores", a="Estudantes e educadores", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Duolingo (IA)", u="https://www.duolingo.com", c1=19, f="Aprendizado de idiomas com IA conversacional", a="Estudantes", p="Web, iOS, Android", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Quizlet (Q-Chat)", u="https://quizlet.com", c1=19, f="Flashcards e estudo com tutor de IA", a="Estudantes", p="Web, apps", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Course Hero (IA)", u="https://www.coursehero.com", c1=19, f="Ajuda com exercícios e materiais de estudo", a="Estudantes", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Photomath", u="https://photomath.com", c1=19, f="Resolução de matemática por foto com IA", a="Estudantes", p="iOS, Android, Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Socratic (Google)", u="https://socratic.org", c1=19, f="Assistente de estudo por foto (Google)", a="Estudantes", p="iOS, Android", c="gratuito", r="não", api="não", os="não", reg="mundial", doc=""),
dict(n="Mathpix", u="https://mathpix.com", c1=19, f="OCR de matemática e notas (LaTeX)", a="Estudantes e pesquisadores", p="iOS, Android, Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="DeepL Write (estudo)", u="https://www.deepl.com/write", c1=19, f="Aprimoramento de escrita para estudos", a="Estudantes", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Coursera (IA/coach)", u="https://www.coursera.org", c1=19, f="Cursos online com assistente de IA", a="Estudantes e profissionais", p="Web, apps", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="edX (IA)", u="https://www.edx.org", c1=19, f="Cursos universitários com recursos de IA", a="Estudantes", p="Web, apps", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Synthesia (e-learning)", u="https://www.synthesia.io", c1=19, f="Vídeos de treinamento com avatares de IA", a="L&D corporativo", p="Web", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Gradescope", u="https://www.gradescope.com", c1=19, f="Correção automatizada de provas (IA)", a="Professores", p="Web", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Brainly (IA)", u="https://brainly.com", c1=19, f="Respostas para lições com IA", a="Estudantes", p="Web, apps", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Knowt", u="https://knowt.com", c1=19, f="Estudo com IA a partir de anotações e PDFs", a="Estudantes", p="Web, iOS, Android", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="HelloTalk (IA)", u="https://www.hellotalk.com", c1=19, f="Troca de idiomas com assistente de IA", a="Aprendizes de idiomas", p="iOS, Android, Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Conker AI", u="https://www.conker.ai", c1=19, f="Criação de quizzes e avaliações com IA", a="Professores", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
# 20. Negócios e produtividade
dict(n="Notion", u="https://www.notion.so", c1=20, f="Espaço de trabalho com IA integrada", a="Equipes e indivíduos", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Microsoft 365 Copilot", u="https://www.microsoft.com/microsoft-365/copilot", c1=20, f="Assistente de IA no Word, Excel, Outlook", a="Empresas", p="Web, desktop, mobile", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Google Workspace (Gemini)", u="https://workspace.google.com", c1=20, f="IA no Docs, Sheets, Gmail", a="Empresas", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Slack AI", u="https://slack.com", c1=20, f="Resumos e buscas com IA no Slack", a="Equipes", p="Web, apps, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Todoist (IA)", u="https://todoist.com", c1=20, f="Gestão de tarefas com assistente de IA", a="Profissionais", p="Web, apps", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Motion", u="https://www.usemotion.com", c1=20, f="Agenda automática e gerenciamento de projetos com IA", a="Profissionais", p="Web, apps", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Mem (IA)", u="https://get.mem.ai", c1=20, f="Bloco de notas com IA que organiza sozinho", a="Profissionais", p="Web, iOS, Android", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Reclaim AI", u="https://reclaim.ai", c1=20, f="Agendamento inteligente de tarefas e hábitos", a="Equipes", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Otter (reuniões)", u="https://otter.ai", c1=20, f="Notas automáticas de reuniões", a="Equipes", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Airtable AI", u="https://www.airtable.com", c1=20, f="Banco de dados visual com IA", a="Equipes", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Coda (IA)", u="https://coda.io", c1=20, f="Documentos colaborativos com IA", a="Equipes", p="Web, apps", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Monday.com (IA)", u="https://monday.com", c1=20, f="Gestão de projetos com IA", a="Equipes", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="ClickUp (IA)", u="https://clickup.com", c1=20, f="Produtividade e projetos com IA", a="Equipes", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Trello (Atlassian IA)", u="https://trello.com", c1=20, f="Quadros Kanban com recursos de IA", a="Equipes", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Zapier (produtividade)", u="https://zapier.com", c1=20, f="Automação de produtividade com IA", a="Profissionais", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Google Keep (IA)", u="https://keep.google.com", c1=20, f="Notas com recursos de IA do Google", a="Público geral", p="Web, Android, iOS", c="gratuito", r="sim", api="não", os="não", reg="mundial", doc=""),
# 21. Atendimento ao cliente
dict(n="Intercom Fin", u="https://www.intercom.com", c1=21, f="Suporte ao cliente com agente de IA (Fin)", a="Empresas SaaS", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Zendesk AI", u="https://www.zendesk.com", c1=21, f="Atendimento com IA (bots e respostas)", a="Empresas", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Freshdesk (Freddy IA)", u="https://www.freshworks.com/freshdesk", c1=21, f="Helpdesk com copiloto de IA", a="Empresas", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Zoho Desk (Zia)", u="https://www.zoho.com/desk", c1=21, f="Suporte com assistente de IA Zia", a="Empresas", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Gorgias (IA)", u="https://www.gorgias.com", c1=21, f="Suporte de e-commerce com automação de IA", a="Lojas online", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Ada", u="https://www.ada.cx", c1=21, f="Agentes de IA para CX em escala", a="Grandes empresas", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Crisp (IA)", u="https://crisp.chat", c1=21, f="Chat de suporte com IA", a="Startups e PMEs", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="LivePerson (IA)", u="https://www.liveperson.com", c1=21, f="Conversas de atendimento com IA", a="Grandes marcas", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Forethought", u="https://forethought.ai", c1=21, f="Resolução automática de tickets com IA", a="Empresas", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Hiver (IA)", u="https://hiverhq.com", c1=21, f="Suporte ao cliente no Gmail com IA", a="PMEs", p="Web, extensão", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="SupportLogic", u="https://supportlogic.io", c1=21, f="Análise de sentimento do suporte com IA", a="Empresas", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Kustomer (IA)", u="https://www.kustomer.com", c1=21, f="Plataforma de atendimento com IA", a="Empresas", p="Web, API", c="pago", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Re:amaze", u="https://www.reamaze.com", c1=21, f="Atendimento omnicanal com IA", a="PMEs e lojas", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Tidio (IA)", u="https://www.tidio.com", c1=21, f="Chat e chatbot com IA para lojas", a="Lojas online", p="Web, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
# 22. Reuniões e produtividade corporativa
dict(n="Zoom AI Companion", u="https://www.zoom.com", c1=22, f="Resumos e assistência em reuniões do Zoom", a="Empresas", p="Web, desktop, mobile, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Microsoft Teams (Copilot)", u="https://www.microsoft.com/microsoft-teams", c1=22, f="Reuniões com transcrição e resumo por IA", a="Empresas", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Google Meet (Gemini)", u="https://meet.google.com", c1=22, f="Notas e resumos com IA no Meet", a="Empresas", p="Web, apps, API", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Otter.ai", u="https://otter.ai", c1=22, f="Transcrição e resumo de reuniões", a="Equipes", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Fireflies.ai", u="https://fireflies.ai", c1=22, f="Assistente de reuniões com busca", a="Equipes", p="Web, apps, API", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="Fathom", u="https://fathom.video", c1=22, f="Notas e destaques automáticos de reuniões", a="Vendas e equipes", p="Web", c="freemium", r="sim", api="sim", os="não", reg="mundial", doc=""),
dict(n="tl;dv", u="https://tldv.io", c1=22, f="Gravação e resumo de reuniões com IA", a="Equipes", p="Web, extensão", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Sembly", u="https://www.sembly.ai", c1=22, f="Assistente de reuniões com minutas", a="Equipes", p="Web, apps", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="MeetGeek", u="https://meetgeek.ai", c1=22, f="Gravação, transcrição e insights de reuniões", a="Equipes", p="Web", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Supernormal", u="https://supernormal.com", c1=22, f="Notas de reunião geradas por IA", a="Equipes", p="Web, extensão", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="Krisp", u="https://krisp.ai", c1=22, f="Cancelamento de ruído e transcrição ao vivo", a="Profissionais", p="Windows, macOS, apps", c="freemium", r="sim", api="não", os="não", reg="mundial", doc=""),
dict(n="OtterPilot", u="https://otter.ai/pilot", c1=22, f="Copiloto de reuniões com ações automáticas", a="Equipes", p="Web, apps", c="pago", r="sim", api="não", os="não", reg="mundial", doc=""),
]
